apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cloud-native-app
  labels:
    app: backend
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.database.config.name | quote }}
  DB_USER: {{ .Values.database.config.user | quote }}
